Traceback (most recent call last):
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/nils/miniconda3/envs/agi-jb/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# erstellt eine Liste von Zufallszahlen (lernen wir zu einem sp√§teren Zeitpunkt)
a = [random.randrange(1, 10) for x in range(0,100)]

# visualisiert die zuf√§llig generierten Zahl in Form eines Histogramms (lernen wir ebenfalls sp√§ter)
pd.Series(a).plot(kind = "hist", bins = range(1,11), edgecolor = "black", align = "left", xticks = range(1,10))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_63564/44370372.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# visualisiert die zuf√§llig generierten Zahl in Form eines Histogramms (lernen wir ebenfalls sp√§ter)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mpd[0m[0;34m.[0m[0mSeries[0m[0;34m([0m[0ma[0m[0;34m)[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mkind[0m [0;34m=[0m [0;34m"hist"[0m[0;34m,[0m [0mbins[0m [0;34m=[0m [0mrange[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m11[0m[0;34m)[0m[0;34m,[0m [0medgecolor[0m [0;34m=[0m [0;34m"black"[0m[0;34m,[0m [0malign[0m [0;34m=[0m [0;34m"left"[0m[0;34m,[0m [0mxticks[0m [0;34m=[0m [0mrange[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m10[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

