Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import geopandas as gpd

wald = gpd.read_file("data/wald.gpkg") # <- importiert das File "wald.gpkg"

wald
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mCPLE_OpenFailedError[0m                      Traceback (most recent call last)
[0;32mfiona/_shim.pyx[0m in [0;36mfiona._shim.gdal_open_vector[0;34m()[0m

[0;32mfiona/_err.pyx[0m in [0;36mfiona._err.exc_wrap_pointer[0;34m()[0m

[0;31mCPLE_OpenFailedError[0m: data/wald.gpkg: No such file or directory

During handling of the above exception, another exception occurred:

[0;31mDriverError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_2165/2334884498.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mgeopandas[0m [0;32mas[0m [0mgpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mwald[0m [0;34m=[0m [0mgpd[0m[0;34m.[0m[0mread_file[0m[0;34m([0m[0;34m"data/wald.gpkg"[0m[0;34m)[0m [0;31m# <- importiert das File "wald.gpkg"[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mwald[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/geopandas/io/file.py[0m in [0;36m_read_file[0;34m(filename, bbox, mask, rows, **kwargs)[0m
[1;32m    158[0m [0;34m[0m[0m
[1;32m    159[0m     [0;32mwith[0m [0mfiona_env[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 160[0;31m         [0;32mwith[0m [0mreader[0m[0;34m([0m[0mpath_or_bytes[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m [0;32mas[0m [0mfeatures[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    161[0m [0;34m[0m[0m
[1;32m    162[0m             [0;31m# In a future Fiona release the crs attribute of features will[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/fiona/env.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m    406[0m     [0;32mdef[0m [0mwrapper[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    407[0m         [0;32mif[0m [0mlocal[0m[0;34m.[0m[0m_env[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 408[0;31m             [0;32mreturn[0m [0mf[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    409[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    410[0m             [0;32mif[0m [0misinstance[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mstr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/fiona/__init__.py[0m in [0;36mopen[0;34m(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)[0m
[1;32m    255[0m         [0;32mif[0m [0mmode[0m [0;32min[0m [0;34m([0m[0;34m'a'[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    256[0m             c = Collection(path, mode, driver=driver, encoding=encoding,
[0;32m--> 257[0;31m                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
[0m[1;32m    258[0m         [0;32melif[0m [0mmode[0m [0;34m==[0m [0;34m'w'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    259[0m             [0;32mif[0m [0mschema[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/fiona/collection.py[0m in [0;36m__init__[0;34m(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)[0m
[1;32m    160[0m             [0;32mif[0m [0mself[0m[0;34m.[0m[0mmode[0m [0;34m==[0m [0;34m'r'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    161[0m                 [0mself[0m[0;34m.[0m[0msession[0m [0;34m=[0m [0mSession[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 162[0;31m                 [0mself[0m[0;34m.[0m[0msession[0m[0;34m.[0m[0mstart[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    163[0m             [0;32melif[0m [0mself[0m[0;34m.[0m[0mmode[0m [0;32min[0m [0;34m([0m[0;34m'a'[0m[0;34m,[0m [0;34m'w'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    164[0m                 [0mself[0m[0;34m.[0m[0msession[0m [0;34m=[0m [0mWritingSession[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32mfiona/ogrext.pyx[0m in [0;36mfiona.ogrext.Session.start[0;34m()[0m

[0;32mfiona/_shim.pyx[0m in [0;36mfiona._shim.gdal_open_vector[0;34m()[0m

[0;31mDriverError[0m: data/wald.gpkg: No such file or directory
DriverError: data/wald.gpkg: No such file or directory

