Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# MusterlÃ¶sung

zeckenstiche_buffer = zeckenstiche.buffer(12)
zeckenstiche_buffer.explore()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/geopandas/explore.py[0m in [0;36m_explore[0;34m(df, column, cmap, color, m, tiles, attr, tooltip, popup, highlight, categorical, legend, scheme, k, vmin, vmax, width, height, categories, classification_kwds, control_scale, marker_type, marker_kwds, style_kwds, highlight_kwds, missing_kwds, tooltip_kwds, popup_kwds, legend_kwds, **kwargs)[0m
[1;32m    250[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 251[0;31m         [0;32mimport[0m [0mbranca[0m [0;32mas[0m [0mbc[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    252[0m         [0;32mimport[0m [0mfolium[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'branca'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_1980/2644057389.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mzeckenstiche_buffer[0m [0;34m=[0m [0mzeckenstiche[0m[0;34m.[0m[0mbuffer[0m[0;34m([0m[0;36m12[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mzeckenstiche_buffer[0m[0;34m.[0m[0mexplore[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/geopandas/geoseries.py[0m in [0;36mexplore[0;34m(self, *args, **kwargs)[0m
[1;32m    813[0m     [0;32mdef[0m [0mexplore[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    814[0m         [0;34m"""Interactive map based on folium/leaflet.js"""[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 815[0;31m         [0;32mreturn[0m [0m_explore_geoseries[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    816[0m [0;34m[0m[0m
[1;32m    817[0m     [0;32mdef[0m [0mexplode[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mignore_index[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m [0mindex_parts[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/geopandas/explore.py[0m in [0;36m_explore_geoseries[0;34m(s, color, m, tiles, attr, highlight, width, height, control_scale, marker_type, marker_kwds, style_kwds, highlight_kwds, **kwargs)[0m
[1;32m    898[0m         [0mstyle_kwds[0m[0;34m=[0m[0mstyle_kwds[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    899[0m         [0mhighlight_kwds[0m[0;34m=[0m[0mhighlight_kwds[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 900[0;31m         [0;34m**[0m[0mkwargs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    901[0m     )

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/geopandas/explore.py[0m in [0;36m_explore[0;34m(df, column, cmap, color, m, tiles, attr, tooltip, popup, highlight, categorical, legend, scheme, k, vmin, vmax, width, height, categories, classification_kwds, control_scale, marker_type, marker_kwds, style_kwds, highlight_kwds, missing_kwds, tooltip_kwds, popup_kwds, legend_kwds, **kwargs)[0m
[1;32m    257[0m     [0;32mexcept[0m [0;34m([0m[0mImportError[0m[0;34m,[0m [0mModuleNotFoundError[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    258[0m         raise ImportError(
[0;32m--> 259[0;31m             [0;34m"The 'folium', 'matplotlib' and 'mapclassify' packages are required for "[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    260[0m             [0;34m"'explore()'. You can install them using "[0m[0;34m[0m[0;34m[0m[0m
[1;32m    261[0m             [0;34m"'conda install -c conda-forge folium matplotlib mapclassify' "[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: The 'folium', 'matplotlib' and 'mapclassify' packages are required for 'explore()'. You can install them using 'conda install -c conda-forge folium matplotlib mapclassify' or 'pip install folium matplotlib mapclassify'.
ImportError: The 'folium', 'matplotlib' and 'mapclassify' packages are required for 'explore()'. You can install them using 'conda install -c conda-forge folium matplotlib mapclassify' or 'pip install folium matplotlib mapclassify'.

